### ISSUE TITLE
demo权限缺少

### ISSUE THREAD

**Issue by MartinDong** [Curzibn/Luban#109]
FATAL EXCEPTION: ModernAsyncTask #1
                                                   Process: top.zibin.luban.example, PID: 12701
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:833)
                                                    Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=12701, uid=10430 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                       at android.os.Parcel.readException(Parcel.java:1602)
                                                       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                       at android.content.ContentResolver.query(ContentResolver.java:502)
                                                       at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:33)
                                                       at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
                                                       at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
                                                       at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
                                                       at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
                                                       at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
                                                       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
                                                       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
                                                       at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                       at java.lang.Thread.run(Thread.java:833)

**Comment by Curzibn** [comment]
新版已解决。
