### ISSUE TITLE
获取不到图片宽高抛出 java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by myhcqgithub** [Curzibn/Luban#116]
java.lang.ArithmeticException: divide by zero
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at top.zibin.luban.Luban.thirdCompress(Luban.java:251)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at top.zibin.luban.Luban.access$200(Luban.java:25)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at top.zibin.luban.Luban$10.call(Luban.java:194)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at top.zibin.luban.Luban$10.call(Luban.java:191)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
03-15 10:33:21.202 8841-8841/com.ems358.cms W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10346)

**Comment by woniu0936** [comment]
我也遇到了这个问题，你解决了吗？ @myhcqgithub

**Comment by myhcqgithub** [comment]
@woniu0936  我自己写了个图片加载库，不使用相册的uri 解决问题

**Comment by woniu0936** [comment]
给个链接看看 @myhcqgithub

**Comment by myhcqgithub** [comment]
@woniu0936  什么链接？

**Comment by woniu0936** [comment]
@myhcqgithub  你写的那个图片加载库

**Comment by myhcqgithub** [comment]
暂未开源

**Comment by lorensong** [comment]
这个问题我遇到过,原因出现在oppo手机上.一般情况下,使用Luban返回的file://XXXX ,但是在oppo手机上返回的是uri:xxxxx 所以,我们对返回的值进行处理一下即可,如果是uri返回,那我们从再去从uri中获取图片信息.@myhcqgithub

**Comment by myhcqgithub** [comment]
@lorensong  这个情况我知道 我最后选择了自己写图片选择 更利于扩展
