### ISSUE TITLE
压缩多张图片出现多张路径重复？

### ISSUE THREAD

**Issue by icuihai** [Curzibn/Luban#120]
压缩多张图片出现重复的情况可以试下这个改进的Luban压缩库https://github.com/icuihai/AdvancedLuban

**Comment by AndroidDevo** [comment]
我也出现这个问题

**Comment by lt13982250340** [comment]
我也出现这个问题，怎么解决？求大神赐教

**Comment by XConstantine** [comment]
https://github.com/XConstantine/Luban

**Comment by lvfaqiang** [comment]
@XConstantine 哥们，你的那个compile 依赖导入不成功啊。

**Comment by XConstantine** [comment]
@lvfaqiang 要在project的build.gradle中加入` maven { url 'https://jitpack.io' }  `
![image](https://cloud.githubusercontent.com/assets/10413226/24756007/d81bf338-1b0e-11e7-9ac7-916896cd9f65.png)

**Comment by Troll4it** [comment]
@XConstantine 

  java.io.IOException: Invalid marker: 89
                                                                        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1604)
                                                                        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1335)
                                                                        at android.media.ExifInterface.<init>(ExifInterface.java:1053)
                                                                        at top.zibin.luban.Luban.getImageSpinAngle(Luban.java:409)
                                                                        at top.zibin.luban.Luban.thirdCompress(Luban.java:242)
                                                                        at top.zibin.luban.Luban.access$200(Luban.java:26)
                                                                        at top.zibin.luban.Luban$12$1.call(Luban.java:227)
                                                                        at top.zibin.luban.Luban$12$1.call(Luban.java:224)
                                                                        at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:66)
                                                                        at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:284)
                                                                        at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
                                                                        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.setProducer(OnSubscribeConcatMap.java:329)
                                                                        at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
                                                                        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:146)
                                                                        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:137)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
                                                                        at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
                                                                        at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:117)
                                                                        at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
                                                                        at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                        at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
                                                                        at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
                                                                        at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                        at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                        at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:831)

**Comment by Troll4it** [comment]
@XConstantine 用了出现这个问题，怎么办，急需

**Comment by Troll4it** [comment]
@XConstantine   那段代码
        return Luban.get(MyApplication.getContext())
                .load(list_file)
                .putGear(Luban.THIRD_GEAR)
                .asList()
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.io())
                .doOnError(Throwable::printStackTrace)
                .onErrorResumeNext(throwable -> {
                    return Observable.empty();
                })
                .flatMap(bytes -> {
                    MultipartBody.Builder builder = new MultipartBody.Builder().setType(MultipartBody.FORM).addFormDataPart("data", data);
                    for (int i = 0; i < list_file.size(); i++) {
                        builder.addFormDataPart("img" + i, list_file.get(i).getName().replaceFirst("gif$", "png"), RequestBody.create(MediaType.parse("multipart/form-data"), list_file.get(i)));
                    }
                    MultipartBody build = builder.build();

                    return ApiWrapper.getInstance().UpRefundData(build);
                });
    }

**Comment by XConstantine** [comment]
![image](https://cloud.githubusercontent.com/assets/10413226/25929976/13bf4f10-3636-11e7-9a08-43afe14010c6.png)
409行IOException，应该是你的图片path有问题

**Comment by pruas** [comment]
可以试试 https://github.com/pruas/Biscuit
