### ISSUE TITLE
luban api<=19 报错

### ISSUE THREAD

**Issue by ysq1993** [Curzibn/Luban#138]
Process: com.cheche365.cheche.android, PID: 2965
                                                                            java.lang.NoClassDefFoundError: top.zibin.luban.Luban
                                                                                at com.cheche365.cheche.android.ui.AnXinUi.AxUploadActivity$GroupImgAdapter.setUri(AxUploadActivity.java:622)
                                                                                at com.cheche365.cheche.android.ui.AnXinUi.AxUploadActivity.onActivityResult(AxUploadActivity.java:810)
                                                                                at android.app.Activity.dispatchActivityResult(Activity.java:5423)
                                                                                at android.app.ActivityThread.deliverResults(ActivityThread.java:3361)
                                                                                at android.app.ActivityThread.handleSendResult(ActivityThread.java:3408)
                                                                                at android.app.ActivityThread.access$1300(ActivityThread.java:135)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by iceuncle** [comment]
这个问题解决了吗？我也遇到了
