### ISSUE TITLE
有些图片一直报这个错java.io.IOException: Invalid marker: 52什么情况

### ISSUE THREAD

**Issue by MirkoWu** [Curzibn/Luban#148]
Invalid image.
java.io.IOException: Invalid marker: 52
    at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1627)
    at android.media.ExifInterface.loadAttributes(ExifInterface.java:1353)
    at android.media.ExifInterface.<init>(ExifInterface.java:1070)
    at me.shaohui.advancedluban.LubanCompresser.getImageSpinAngle(LubanCompresser.java:294)
    at me.shaohui.advancedluban.LubanCompresser.thirdCompress(LubanCompresser.java:91)
    at me.shaohui.advancedluban.LubanCompresser.compressImage(LubanCompresser.java:75)
    at me.shaohui.advancedluban.LubanCompresser.access$100(LubanCompresser.java:28)
    at me.shaohui.advancedluban.LubanCompresser$1.call(LubanCompresser.java:44)
    at me.shaohui.advancedluban.LubanCompresser$1.call(LubanCompresser.java:41)
    at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
    at io.reactivex.Observable.subscribe(Observable.java:10700)
    at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:833)

**Comment by Curzibn** [comment]
png没有Exif信息，目前已经在1.1.1版本做了判断修复该问题
