### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by providerwu** [Curzibn/Luban#150]
偶尔会出现的问题，小白表示，不知道是我这边代码问题还是。。。，参照文档写的压缩方法，望抽空帮忙看下，非常感谢

**android 4.4.4 (19)，Xiaomi:HM NOTE 1LTE:armeabi-v7a  未 Root**

java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(SourceFile:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:623)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:599)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
	at top.zibin.luban.Luban.compress(SourceFile:363)
	at top.zibin.luban.Luban.compress(SourceFile:405)
	at top.zibin.luban.Luban.thirdCompress(SourceFile:257)
	at top.zibin.luban.Luban.access$200(SourceFile:25)
	at top.zibin.luban.Luban$8.call(SourceFile:131)
	at top.zibin.luban.Luban$8.call(SourceFile:128)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(SourceFile:66)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(SourceFile:284)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(SourceFile:80)
	at rx.j.setProducer(SourceFile:211)
	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(SourceFile:76)
	at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(SourceFile:99)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(SourceFile:146)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(SourceFile:137)
	at rx.internal.operators.OnSubscribeLift.call(SourceFile:50)
	at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
	at rx.d.unsafeSubscribe(SourceFile:8666)
	at rx.internal.operators.OperatorSubscribeOn$1.call(SourceFile:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(SourceFile:220)
	at rx.internal.schedulers.ScheduledAction.run(SourceFile:55)
	... 7 more

----------------------------------------------------------------------------
**android 4.4.4 (19)，vivo:vivo Y23L:armeabi-v7a 未 Root**

java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(SourceFile:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.OutOfMemoryError
	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:122)
	at top.zibin.luban.Luban.saveImage(SourceFile:447)
	at top.zibin.luban.Luban.compress(SourceFile:409)
	at top.zibin.luban.Luban.thirdCompress(SourceFile:257)
	at top.zibin.luban.Luban.access$200(SourceFile:25)
	at top.zibin.luban.Luban$8.call(SourceFile:131)
	at top.zibin.luban.Luban$8.call(SourceFile:128)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(SourceFile:66)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(SourceFile:284)
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(SourceFile:80)
	at rx.j.setProducer(SourceFile:211)
	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(SourceFile:76)
	at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(SourceFile:99)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(SourceFile:146)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(SourceFile:137)
	at rx.internal.operators.OnSubscribeLift.call(SourceFile:50)
	at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
	at rx.d.unsafeSubscribe(SourceFile:8666)
	at rx.internal.operators.OperatorSubscribeOn$1.call(SourceFile:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(SourceFile:220)
	at rx.internal.schedulers.ScheduledAction.run(SourceFile:55)
	... 7 more

**Comment by Curzibn** [comment]
请使用最新版看看是否依然存在这种情况
