### ISSUE TITLE
N985st 4.4 机型 miui oom( 手机拍照的图片, 大小1.37MB  , 3120 * 4208)

### ISSUE THREAD

**Issue by AegisLee** [Curzibn/Luban#17]
必现, 或许和图片选择库有一定的关系, 滑到最底部, 选择那张图片, 点完成, 会oom;

```
08-04 12:05:12.904 32005-32005/top.zibin.luban.example E/dalvikvm-heap: Out of memory on a 13128976-byte allocation.
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm: "main" prio=5 tid=1 RUNNABLE
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x4161ee58 self=0x4153b518
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:   | sysTid=32005 nice=0 sched=0/0 cgrp=apps handle=1074413908
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:   | state=R schedstat=( 6918152497 1493630453 7279 ) utm=644 stm=47 core=2
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:627)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:603)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at top.zibin.luban.Luban.compress(Luban.java:317)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at top.zibin.luban.Luban.compress(Luban.java:359)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at top.zibin.luban.Luban.thirdCompress(Luban.java:213)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at top.zibin.luban.Luban.asObservable(Luban.java:158)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at top.zibin.luban.example.MainActivity.compressWithRx(MainActivity.java:96)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at top.zibin.luban.example.MainActivity.onActivityResult(MainActivity.java:134)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.app.Activity.dispatchActivityResult(Activity.java:5434)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3410)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.app.ActivityThread.access$1300(ActivityThread.java:141)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.os.Looper.loop(Looper.java:136)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5113)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
08-04 12:05:12.904 32005-32005/top.zibin.luban.example D/skia: --- decoder->decode returned false
08-04 12:05:12.904 32005-32005/top.zibin.luban.example D/AndroidRuntime: Shutting down VM
08-04 12:05:12.904 32005-32005/top.zibin.luban.example W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4161dd58)
```

**Comment by Curzibn** [comment]
我这边并未出现这种情况，估计是图片选择组件的问题。
你试下不用图片组件还会不会！

**Comment by AegisLee** [comment]
使用的系统相册
