### ISSUE TITLE
华为6.0手机报异常

### ISSUE THREAD

**Issue by yyzl0418** [Curzibn/Luban#176]
UncaughtException detected: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                   at top.zibin.luban.Engine.rotatingImage(Engine.java:93)
                                                   at top.zibin.luban.Engine.compress(Engine.java:103)
                                                   at top.zibin.luban.Luban$1.run(Luban.java:106)
                                                   at java.lang.Thread.run(Thread.java:833)

**Comment by zxyaust** [comment]
我也发现这个问题了

**Comment by w499927181** [comment]
+1

**Comment by HeMing123** [comment]
+1

**Comment by chenzheng8975** [comment]
+1

**Comment by coolxiao** [comment]
+1

**Comment by Curzibn** [comment]
已发布Luban 2，请查看最新项目说明
