### ISSUE TITLE
luban api <= 19 报错异常

### ISSUE THREAD

**Issue by Djwei** [Curzibn/Luban#177]
android 4.4.4  压缩图片 file == null 
  AndroidRuntime: FATAL EXCEPTION: Thread-10423
                               Process: , PID: 21425
                              java.lang.NullPointerException: file == null
                                     at java.io.FileOutputStream.<init>(FileOutputStream.java:85)
                                     at java.io.FileOutputStream.<init>(FileOutputStream.java:73)
                                     at top.zibin.luban.Engine.compress(Engine.java:107)
                                     at top.zibin.luban.Luban$1.run(Luban.java:106)
                                     at java.lang.Thread.run(Thread.java:841)
测试的6.0 以及 7.0 没有问题   我已经将Uri 地址转化为file绝对路径了

**Comment by Curzibn** [comment]
Uri版本在1.1.4提供
