### ISSUE TITLE
OOM问题，比较难复现，但确实存在

### ISSUE THREAD

**Issue by Yanqilong** [Curzibn/Luban#184]
调用Luban.with(getApplicationContext()).load(file).get()，出现OOM，请大大查看原因。

08-21 15:37:00.755 29433-8961/com.newseax.tutor E/Tinker.SampleUncaughtExHandler: uncaughtException:Failed to allocate a 12979212 byte allocation with 9991920 free bytes and 9MB until OOM
08-21 15:37:00.767 29433-8961/com.newseax.tutor E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.OutOfMemoryError: Failed to allocate a 12979212 byte allocation with 9991920 free bytes and 9MB until OOM
                                                                              at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                              at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                              at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:639)
                                                                              at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:615)
                                                                              at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
                                                                              at top.zibin.luban.Engine.compress(Engine.java:100)
                                                                              at top.zibin.luban.Luban.get(Luban.java:119)
                                                                              at top.zibin.luban.Luban.access$700(Luban.java:15)
                                                                              at top.zibin.luban.Luban$Builder.get(Luban.java:171)
                                                                              at com.newseax.tutor.service.DynamicPublishService$2.apply(DynamicPublishService.java:179)
                                                                              at com.newseax.tutor.service.DynamicPublishService$2.apply(DynamicPublishService.java:176)
                                                                              at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:62)
                                                                              at io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:179)
                                                                              at io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:121)
                                                                              at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:152)
                                                                              at io.reactivex.internal.operators.flowable.FlowableToListSingle$ToListSubscriber.onSubscribe(FlowableToListSingle.java:84)
                                                                              at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:66)
                                                                              at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:68)
                                                                              at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:46)
                                                                              at io.reactivex.Flowable.subscribe(Flowable.java:12885)
                                                                              at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:36)
                                                                              at io.reactivex.Flowable.subscribe(Flowable.java:12885)
                                                                              at io.reactivex.internal.operators.flowable.FlowableToListSingle.subscribeActual(FlowableToListSingle.java:57)
                                                                              at io.reactivex.Single.subscribe(Single.java:2657)
                                                                              at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                              at io.reactivex.Scheduler$1.run(Scheduler.java:134)
                                                                              at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                              at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by LABELNET** [comment]
连续进行4张图片压缩就OOM了，怎么解决？

**Comment by jinbolx** [comment]
![image](https://user-images.githubusercontent.com/14304952/29956748-cdfb3e82-8f1b-11e7-921a-06f30149a801.png)
我猜你大概也是这个原因：看一下代码注释掉的部分，这里他交换宽高写错了，导致部分情况下压缩会oom，你分别用他的demo测试一下1920x1080 和1080x1920的图片就会发现问题

**Comment by Yanqilong** [comment]
@LABELNET 好久没开 issues 了
你这个问题我也碰到过，解决办法： 结合 RX 操作符执行在i/o线程 + LuBan 同步压缩来解决你这个问题
代码：
```ruby
        final List<File> rawFileList = new ArrayList<>();
        Flowable.fromIterable(rawFileList)
                .map(new Function<File, File>() {
                    @Override
                    public File apply(File file) throws Exception {
                        return top.zibin.luban.Luban.with(getApplicationContext()).load(file).get().get(0);
                    }
                })
                .toList()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<List<File>>() {

                    @Override
                    public void accept(List<File> fileList) throws Exception {
                     //得到压缩后的图片

                });
```
