### ISSUE TITLE
java.lang.NullPointerException: android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by Linfeng2010** [Curzibn/Luban#209]
at top.zibin.luban.Engine.rotatingImage(Engine.java:84)
                                                                      at top.zibin.luban.Engine.compress(Engine.java:94)
                                                                      at top.zibin.luban.Luban$1.run(Luban.java:126)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by qianshui423** [comment]
这个bug我也碰到了，一模一样，大佬解决下升个版本怎么样噢

**Comment by Scorpiolol** [comment]
同样遇到了这个问题，跪求解决方法

**Comment by yyt231** [comment]
有谁解决了这个问题了？

**Comment by puyunfeng** [comment]
有谁解决了这个问题了？

**Comment by Curzibn** [comment]
已发布Luban 2，请查看最新项目说明
