### ISSUE TITLE
压缩OutOfMemoryError

### ISSUE THREAD

**Issue by hudan2714** [Curzibn/Luban#211]
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:636)
	at top.zibin.luban.Engine.rotatingImage(Engine.java:84)
	at top.zibin.luban.Engine.compress(Engine.java:94)
	at top.zibin.luban.Luban$1.run(Luban.java:126)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

**Comment by kingcxsc** [comment]
I met the question too
