### ISSUE TITLE
A resource was acquired at attached stack trace but never released

### ISSUE THREAD

**Issue by lijingnan** [Curzibn/Luban#222]
StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
              java.lang.Throwable: Explicit termination method 'close' not called
                  at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                  at java.io.FileInputStream.<init>(FileInputStream.java:78)
                  at java.io.FileInputStream.<init>(FileInputStream.java:103)
                  at android.media.ExifInterface.loadAttributes(ExifInterface.java:1334)
                  at android.media.ExifInterface.<init>(ExifInterface.java:1053)
                  at top.zibin.luban.Engine.<init>(Engine.java:25)
                  at top.zibin.luban.Luban.get(Luban.java:156)
                  at top.zibin.luban.Luban.access$1000(Luban.java:20)
                  at top.zibin.luban.Luban$Builder.get(Luban.java:254)
望修改。

**Comment by Curzibn** [comment]
已发布Luban 2，请查看最新项目说明
