### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Landroid/support/media/ExifInterface

### ISSUE THREAD

**Issue by RoboyCore** [Curzibn/Luban#244]
I use luban load photo from uri and cause this error, phone MODEL =is Meizu PRO 6 Plus (Android N)
   java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/media/ExifInterface;
                                                                   at top.zibin.luban.Engine.<init>(Engine.java:25)
                                                                   at top.zibin.luban.Luban$1.run(Luban.java:131)
                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                   at java.lang.Thread.run(Thread.java:761)

**Comment by AkkunYo** [comment]
implementation 'top.zibin:Luban:1.1.3'

**Comment by jp1017** [comment]
用1.1.3版本或者1.1.4版本添加依赖:
>    implementation "com.android.support:exifinterface:27.1.1"

**Comment by williamsim** [comment]
哎
