### ISSUE TITLE
java.lang.NullPointerException: android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by coolxiao** [Curzibn/Luban#257]
这个问题怎么解决啊

**Comment by bleupierre** [comment]
我也遇到这个问题了

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at top.zibin.luban.b.a(Engine.java:84)
	at top.zibin.luban.b.a(Engine.java:94)
	at top.zibin.luban.d.a(Luban.java:187)
	at top.zibin.luban.d.a(Luban.java:24)
	at top.zibin.luban.d$1.run(Luban.java:140)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by coolxiao** [comment]
@bleupierre 解决了吗

**Comment by Curzibn** [comment]
已发布Luban 2，请查看最新项目说明
