### ISSUE TITLE
压缩报错

### ISSUE THREAD

**Issue by kulong51** [Curzibn/Luban#283]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
        at top.zibin.luban.Engine.compress(Engine.java:79)
        at top.zibin.luban.Luban.compress(Luban.java:180)
        at top.zibin.luban.Luban.access$700(Luban.java:21)
        at top.zibin.luban.Luban$1.run(Luban.java:135)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    #++++++++++++++++++++++++++++++++++++++++++#

**Comment by itkun2013** [comment]
不能压缩音频流，流错误
stream is wrong,only image
