### ISSUE TITLE
java.lang.OutOfMemoryError  V1.1.8

### ISSUE THREAD

**Issue by JalenFang** [Curzibn/Luban#294]
09-19 06:27:59.281 12283 13652 W art : Throwing OutOfMemoryError "Failed to allocate a 2097164 byte allocation with 674696 free bytes and 658KB until OOM"
7909-19 06:27:59.282 12283 13652 W System.err: java.lang.OutOfMemoryError: Failed to allocate a 2097164 byte allocation with 674696 free bytes and 658KB until OOM
8009-19 06:27:59.282 12283 12283 E Sensors : sendAck failure -1 1
8109-19 06:27:59.282 12283 12283 E Sensors : sendAck failure -1 1
8209-19 06:27:59.282 12283 12283 E Sensors : sendAck failure -1 2
8309-19 06:27:59.282 12283 12283 E Sensors : sendAck failure -1 2
8409-19 06:27:59.282 12283 13652 W System.err: at java.util.Arrays.copyOf(Arrays.java:3256)
8509-19 06:27:59.282 12283 13652 W System.err: at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
8609-19 06:27:59.282 12283 13652 W System.err: at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
8709-19 06:27:59.282 12283 13652 W System.err: at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
8809-19 06:27:59.282 12283 13652 W System.err: at top.zibin.luban.Checker.toByteArray(Checker.java:187)
8909-19 06:27:59.282 12283 13652 W System.err: at top.zibin.luban.Checker.isJPG(Checker.java:27)
9009-19 06:27:59.282 12283 13652 W System.err: at top.zibin.luban.Engine.compress(Engine.java:77)
9109-19 06:27:59.282 12283 13652 W System.err: at top.zibin.luban.Luban.compress(Luban.java:186)
9209-19 06:27:59.282 12283 13652 W System.err: at top.zibin.luban.Luban.get(Luban.java:160)

**Comment by liuhuan8986** [comment]
我也遇到了

**Comment by Curzibn** [comment]
已发布Luban 2，请查看最新项目说明
