### ISSUE TITLE
NullPointerException异常

### ISSUE THREAD

**Issue by xxinjun** [Curzibn/Luban#297]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at top.zibin.luban.Engine.rotatingImage(Unknown Source:10)
	at top.zibin.luban.Engine.compress(Unknown Source:53)
	at top.zibin.luban.Luban.compress(Unknown Source:101)
	at top.zibin.luban.Luban.access$700(Unknown Source:0)
	at top.zibin.luban.Luban$1.run(Unknown Source:26)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by LouXiang** [comment]
解决了吗兄弟，我也遇到了这个问题
