### ISSUE TITLE
boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream) on a null object reference

### ISSUE THREAD

**Issue by YiMenHuiShou** [Curzibn/Luban#317]
机型：vivo y66 系统：Android 6.0.1
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
--
at top.zibin.luban.Engine.compress(Engine.java:95)
at top.zibin.luban.Luban.compress(Luban.java:187)
at top.zibin.luban.Luban.access$700(Luban.java:24)
at top.zibin.luban.Luban$1.run(Luban.java:140)

**Comment by colder112** [comment]
更新到最新的1.1.8版本就好了

**Comment by LouXiang** [comment]
我这边用了1.1.8，有时候还是会出现这个问题

**Comment by 424385117** [comment]
> 更新到最新的1.1.8版本就好了

不行啊更新到1.1.8照样报错

**Comment by wangzhonghao** [comment]
这个问题怎么解决？

**Comment by TopTime1** [comment]
同求怎么解决？

**Comment by Curzibn** [comment]
已发布Luban 2，请查看最新项目说明
