### ISSUE TITLE
Engine 类 compress 方法 tagBitmap 报空指针

### ISSUE THREAD

**Issue by lizixian18** [Curzibn/Luban#318]
Engine 类 compress 方法 tagBitmap 报空指针

**Comment by lll-01** [comment]
```
6561-7285 W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
6561-7285 W/System.err:     at top.zibin.luban.Engine.compress(Engine.java:79)
6561-7285 W/System.err:     at top.zibin.luban.Luban.get(Luban.java:152)
6561-7285 W/System.err:     at top.zibin.luban.Luban.access$1100(Luban.java:21)
6561-7285 W/System.err:     at top.zibin.luban.Luban$Builder.get(Luban.java:354)
6561-7285 W/System.err:     at com.yanzhenjie.durban.EditFilterActivity$FileCopyTask.doInBackground(EditFilterActivity.java:541)
6561-7285 W/System.err:     at com.yanzhenjie.durban.EditFilterActivity$FileCopyTask.doInBackground(EditFilterActivity.java:530)
6561-7285 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
6561-7285 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
6561-7285 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
6561-7285 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
6561-7285 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
6561-7285 W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by colder112** [comment]
一样啊,出现在vivo的手机上了.华为和小米就没问题

**Comment by colder112** [comment]
更新到最新的1.1.8就好了

**Comment by colder112** [comment]
不知道你出问题的手机型号是啥...

**Comment by yuanxiangdong** [comment]
同样出现报错！并不是必现，是概率性出现
版本：top.zibin:Luban:1.1.8；
出现机型：一加 A5010；
Android版本：9.0

**Comment by lizixian18** [comment]
如果传入的不是图片格式，就会必现，现在是通过下载源码修改了

**Comment by yuanxiangdong** [comment]
> 如果传入的不是图片格式，就会必现，现在是通过下载源码修改了

传入的是图片，也有概率会出现闪退

**Comment by xingxiang1989** [comment]
同样出现该问题，在vivo x9s，Vivo Nex A

**Comment by fazhongxu** [comment]
- 
![20190315174718](https://user-images.githubusercontent.com/24353536/54423077-c9c82580-474a-11e9-978d-ae81c42b97f3.jpg)

**Comment by fazhongxu** [comment]
虽然外部抛出了IO Exception 并且try catch 住了，但是，人家是NullPointerException  可以在此解决这个bug

**Comment by AnJiuZhe** [comment]
这种是图片损坏了，压缩后会出现这种情况。
我目前是这样处理的，调用压缩前先对bitmap判空处理。
Bitmap bitmap = BitmapFactory.decodeFile(picPath);
 try {
    bitmap.getWidth();
 } catch (Exception e) {
   //图片损坏
    return;
}
//开始压缩
、、、
