### ISSUE TITLE
压缩错误

### ISSUE THREAD

**Issue by qq1191965884** [Curzibn/Luban#349]
java.lang.NullPointerException
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

top.zibin.luban.Engine.rotatingImage(Engine.java:66)
VIVO X21A

**Comment by wuzhenzhen** [comment]
我也遇到一个错误：
java.lang.NullPointerException
        at top.zibin.luban.Engine.rotatingImage(Engine.java:66)
        at top.zibin.luban.Engine.compress(Engine.java:77)
        at top.zibin.luban.Luban.compress(Luban.java:180)
        at top.zibin.luban.Luban.access$700(Luban.java:21)
        at top.zibin.luban.Luban$1.run(Luban.java:135)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:856)

**Comment by hehe1231** [comment]
这个库是不是没人维护了？

**Comment by qq1191965884** [comment]
不知道了，看着上次维护时间挺长了，不过用的多挺多的，不至于吧。我看Pictureselector也在用这个库

**Comment by NickLoveSunny** [comment]
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
java.io.IOException: Invalid byte order: ffff8950
at android.media.ExifInterface.readByteOrder(ExifInterface.java:3191)
at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2501)
at android.media.ExifInterface.getMimeType(ExifInterface.java:2379)
at android.media.ExifInterface.loadAttributes(ExifInterface.java:1801)
at android.media.ExifInterface.(ExifInterface.java:1476)
at com.bumptech.glide.load.resource.bitmap.ExifInterfaceImageHeaderParser.getOrientation(ExifInterfaceImageHeaderParser.java:40)
at com.bumptech.glide.load.ImageHeaderParserUtils.getOrientation(ImageHeaderParserUtils.java:92)
at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:269)
at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:224)
at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:173)
at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:31)
at com.bumptech.glide.load.resource.bitmap.ByteBufferBitmapDecoder.decode(ByteBufferBitmapDecoder.java:14)
at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:92)
at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:70)
at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:59)
at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:524)
at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:488)
at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:474)
at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:390)
at com.bumptech.glide.load.engine.ResourceCacheGenerator.onDataReady(ResourceCacheGenerator.java:123)
at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:70)
at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:102)
at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:276)
at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:929)
at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:431)
