### ISSUE TITLE
不更新了吗？Android R 上报错

### ISSUE THREAD

**Issue by cv0cv0** [Curzibn/Luban#380]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at top.zibin.luban.Luban.getImageCacheFile(Luban.java:60)
        at top.zibin.luban.Luban.compress(Luban.java:170)
        at top.zibin.luban.Luban.access$700(Luban.java:21)
        at top.zibin.luban.Luban$1.run(Luban.java:135)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by javakam** [comment]
适配了 Android Q & Android 11 👉 <https://github.com/javakam/FileOperator/tree/master/library_compressor>
