### ISSUE TITLE
java.lang.NoClassDefFoundError: top.zibin.luban.Preconditions

### ISSUE THREAD

**Issue by Longalei** [Curzibn/Luban#65]
郑哥，你好，Android4.3系统上对图片进行压缩时产生此异常（但是在5.0系统上无异常），思考许久，也未找出原因。所报异常如下：

```
                                                                 java.lang.NoClassDefFoundError: top.zibin.luban.Preconditions
                                                                     at top.zibin.luban.Luban.launch(Luban.java:86)
                                                                     at com.shoneme.xmc.mine.activity.ReleaseVideoActivity.setPicToView(ReleaseVideoActivity.java:423)
                                                                     at com.shoneme.xmc.mine.activity.ReleaseVideoActivity.onActivityResult(ReleaseVideoActivity.java:370)
                                                                     at android.app.Activity.dispatchActivityResult(Activity.java:5563)
                                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3496)
                                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3543)
                                                                     at android.app.ActivityThread.access$1200(ActivityThread.java:159)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
                                                                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Curzibn** [comment]
@Longalei 不好意思现在才有空，请问你这个问题还存在吗？

**Comment by yx19861211** [comment]
存在，所以还是按setfile方法设置值，如果压缩了会按我设置的返回。但是给的按设置默认路径不好使


发送自我的三星 Galaxy 智能手机。
-------- 原始信息 --------由： 郑梓斌 <notifications@github.com> 日期: 16/10/14  16:01  (GMT+08:00) 收件人： Curzibn/Luban <Luban@noreply.github.com> 主题： Re: [Curzibn/Luban] java.lang.NoClassDefFoundError: top.zibin.luban.Preconditions (#65) 
@Longalei 不好意思现在才有空，请问你这个问题还存在吗？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Curzibn/Luban","title":"Curzibn/Luban","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Curzibn/Luban"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Curzibn in #65: @Longalei 不好意思现在才有空，请问你这个问题还存在吗？"}],"action":{"name":"View Issue","url":"https://github.com/Curzibn/Luban/issues/65#issuecomment-253734754"}}}
